# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt
import sys
from Logic import Table
from PyQt5.QtWidgets import *
from PyQt5.QtSql import QSqlDatabase, QSqlTableModel,QSqlQuery
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(Main_Window)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle('曹妃甸南货调写实系统')
        MainWindow.resize(1024, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 228, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.report_model = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.report_model.setObjectName("report_model")
        self.horizontalLayout.addWidget(self.report_model)
        self.input_model = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.input_model.setObjectName("input_model")
        self.horizontalLayout.addWidget(self.input_model)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 90, 1021, 501))
        self.tableView.setObjectName("tableView")
        self.GroupBox = QtWidgets.QComboBox(self.centralwidget)
        self.GroupBox.setGeometry(QtCore.QRect(840, 10, 121, 26))
        self.GroupBox.setObjectName("GroupBox")
        self.GroupBox.addItem("")
        self.GroupBox.addItem("")
        self.GroupBox.addItem("")
        self.GroupBox.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 0, 163, 93))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartTime = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.StartTime.setObjectName("StartTime")
        self.verticalLayout.addWidget(self.StartTime)
        self.EndTime = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.EndTime.setObjectName("EndTime")
        self.verticalLayout.addWidget(self.EndTime)
        self.AggBox = QtWidgets.QComboBox(self.centralwidget)
        self.AggBox.setGeometry(QtCore.QRect(840, 50, 121, 26))
        self.AggBox.setObjectName("AggBox")
        self.AggBox.addItem("")
        self.AggBox.addItem("")
        self.AggBox.addItem("")
        self.AggBox.addItem("")
        self.over_time = QtWidgets.QCheckBox(self.centralwidget)
        self.over_time.setGeometry(QtCore.QRect(560, 10, 71, 31))
        self.over_time.setObjectName("over_time")
        self.output_line = QtWidgets.QLineEdit(self.centralwidget)
        self.output_line.setGeometry(QtCore.QRect(230, 10, 321, 31))
        self.output_line.setObjectName("output_line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 将table函数返回的layout置于tableview控件之中
        self.tableView.setLayout(Table.table(self))

    # ————————————————————————————————————————
    # 定义函数table 返回一个layout

    # ————————————————————————————————————————


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.report_model.setText(_translate("MainWindow", "报表模式"))
        self.input_model.setText(_translate("MainWindow", "输入模式"))
        self.GroupBox.setItemText(0, _translate("MainWindow", "无"))
        self.GroupBox.setItemText(1, _translate("MainWindow", "装车地点"))
        self.GroupBox.setItemText(2, _translate("MainWindow", "到站"))
        self.GroupBox.setItemText(3, _translate("MainWindow", "线路"))
        self.AggBox.setItemText(0, _translate("MainWindow", "无"))
        self.AggBox.setItemText(1, _translate("MainWindow", "用时总和"))
        self.AggBox.setItemText(2, _translate("MainWindow", "用时平均值"))
        self.AggBox.setItemText(3, _translate("MainWindow", "用时极值"))
        self.over_time.setText(_translate("MainWindow", "超时"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    Main_Window = QtWidgets.QMainWindow()
    Ui = Ui_MainWindow()
    # Ui.setupUi(Main_Window)
    Main_Window.show()
    sys.exit(app.exec_())
